///$tab Main
SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$ ###0.00;-$ ###0.00';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='M/D/YYYY';
SET TimestampFormat='M/D/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-US';
SET CreateSearchIndexOnReload=1;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

//creating the variable to define the connection to the data catalog in Qlik Cloud
SET vFileLocation = lib://DataFiles/;

//creating the variable to define our database connection to MS SQL Server
SET vDBConn='ABC';

///$tab DB_Measures
//loading Orders and OrdeDetails tables from ABC database
LIB CONNECT TO $(vDBConn);

Orders:
LOAD OrderID, 
// 	OrderID as OrderRecordCounter,
	1 as OrderRecordCounter, // agregamos contador 
	CustomerID,
    CustomerID as ActiveCustomerID,
	EmployeeID,
    // se crea esto para identificar quien de los empleados es vendedor con el flag en la tabla employees
    EmployeeID as SalesPersonID,
	ShipperID, 
	FreightWeight,
    // se crean categorias de peso de carga con IF()
    IF(FreightWeight<30, 'Light', 
    	if(FreightWeight >= 30 and FreightWeight < 70, 'Medium', 'Heavy'))
        AS FreightWeightCategory,
    // Se crean clases de peso de carga con CLASS() con intervalos de 10 y usamos replace para no tener nombres de intervalos largos
    '>=' & REPLACE(Class(FreightWeight, 10, 'FrWeight'),'<= FrWeight <','<') as FreightClass,
    Date(Floor(OrderDate)) AS OrderDate // Floor () elimina el elemento de tiempo de OrderDate
 where OrderDate < now(); // para que los datos sean hasta la fecha de carga actual 

SELECT OrderID,
	CustomerID,
	EmployeeID,
	ShipperID,
	FreightWeight,
	OrderDate
FROM orders;

//LIB CONNECT TO 'ABC'; - se elimina porque ya se conecto arriba

OrderDetails:
Load *,
	Window(SUM(LineSalesAmount), OrderID) as OrderSalesAmt;

LOAD OrderID, 
	LineNo, 
	ProductID, 
	UnitPrice,
    UnitPrice * Quantity * (1 - Discount) AS LineSalesAmount,
	Quantity, 
	Discount
    // El objetivo de este paso es filtrar la tabla OrderDetails indirectamente usando la función Exists(campo_en_memoria, campo_origen)
where Exists(OrderID,OrderID) // Para cada fila que lee de la base de datos origen, Qlik comprueba si el OrderID entrante existe en la lista de OrderID cargados previamente.
    ;

SELECT OrderID,
	"LineNo",
	ProductID,
	UnitPrice,
	Quantity,
	Discount
FROM orderdetails;

// creamos esta tabla para agrupar OrderDetails
OrderHeader:
Load
	OrderID,
    SUM(LineSalesAmount) AS OrderSalesAmount
Resident OrderDetails
Group by OrderID;

///$tab DB_Dimensions
//loading Customers and Divisions tables from ABC database
LIB CONNECT TO $(vDBConn);

Customers:
LOAD CustomerID, 
	CompanyName, 
	ContactName, 
	City, 
	Country, 
	DivisionID, 
	Address, 
	Fax, 
	Phone, 
	PostalCode, 
	StateProvince;

SELECT CustomerID,
	CompanyName,
	ContactName,
	City,
	Country,
	DivisionID,
	Address,
	Fax,
	Phone,
	PostalCode,
	StateProvince
FROM customers;

Divisions:
LOAD DivisionID, 
	DivisionName;

SELECT DivisionID,
	DivisionName
FROM divisions;


///$tab File_Dimensions
//Employees table load
Employees:
LOAD
    EmpID as EmployeeID,
    //"First Name" as FirstName,
    //"Last Name" as LastName,
    "First Name" &' '& "Last Name" AS FullName,
    DateOfBirth,
    StartDate,
    EndDate,
    OfficeID,
    JobTitle,
    // flag que funciona asi: Busca el campo 'EmpID' en la tabla 'Employees' 
    //y lo compara con el campo 'SalesPersonID' en la tabla 'Orders'
    IF(Exists(SalesPersonID, EmpID),1,0) as SalesPersonFlag
FROM [$(vFileLocation)ABC_employees.xlsx]
(ooxml, embedded labels, table is Employees);

//EmployeeTeam and Teams table load
EmployeeTeam:
LOAD
    EmpID as EmployeeID,
    TeamID
FROM [$(vFileLocation)ABC_teams.xlsx]
(ooxml, embedded labels, table is employee_team);

Team:
LOAD
    TeamID,
    Team
FROM [$(vFileLocation)ABC_teams.xlsx]
(ooxml, embedded labels, table is team);

//Offices table load csv
Offices: 
LOAD
    OfficeID,
    OfficeAddress,
    OfficeCity,
    OfficeCountry,
    OfficeFax,
    OfficePhone,
    OfficePostalCode,
    OfficeStateProvince
FROM [$(vFileLocation)ABC_offices.csv]
(txt, codepage is 28591, embedded labels, delimiter is ',', msq);

//OrgStructure table load archivo ancho fijo 
OrgStructure:
LOAD
    EmpID AS EmployeeID,
    ReportsTo AS ManagerID
FROM [$(vFileLocation)ABC_org_structure.fix]
(txt, codepage is 28591, embedded labels, delimiter is spaces, msq);

// Creacion de una direccion de email para cada empleado, carga de un script 

$(Must_Include=[$(vFileLocation)ABC_GenEmpEmailAddresses.qvs]);




